-- =====================================================
-- MIGRATION COMPLÈTE : Pays manquants + Villes principales
-- Date : 27/05/2026
-- =====================================================

-- =====================================================
-- PARTIE 1 : Ajout des pays manquants (avec continent_id)
-- =====================================================

INSERT INTO countries (id, name, code, continent_id)
SELECT gen_random_uuid(), name, code, continent_id::uuid
FROM (VALUES
    -- Afrique (b6179074-6117-4634-a4e8-92b27d268fb6)
    ('Afrique du Sud', 'ZA', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Soudan', 'SD', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Tanzanie', 'TZ', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Ouganda', 'UG', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Zambie', 'ZM', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Zimbabwe', 'ZW', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Mozambique', 'MZ', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Malawi', 'MW', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Namibie', 'NA', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Botswana', 'BW', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Libye', 'LY', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Tunisie', 'TN', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Mauritanie', 'MR', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Somalie', 'SO', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Sierra Leone', 'SL', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Togo', 'TG', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Libéria', 'LR', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Rwanda', 'RW', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Burundi', 'BI', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Gabon', 'GA', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Guinée équatoriale', 'GQ', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('République du Congo', 'CG', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('République centrafricaine', 'CF', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Tchad', 'TD', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Niger', 'NE', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Mali', 'ML', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Burkina Faso', 'BF', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Guinée', 'GN', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Guinée-Bissau', 'GW', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Gambie', 'GM', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Cap-Vert', 'CV', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Angola', 'AO', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Égypte', 'EG', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Algérie', 'DZ', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    ('Maroc', 'MA', 'b6179074-6117-4634-a4e8-92b27d268fb6'),
    
    -- Europe (810c13b9-f7f1-46b9-9cdc-7b0fb7338b03)
    ('Russie', 'RU', '810c13b9-f7f1-46b9-9cdc-7b0fb7338b03'),
    ('Suède', 'SE', '810c13b9-f7f1-46b9-9cdc-7b0fb7338b03'),
    ('Norvège', 'NO', '810c13b9-f7f1-46b9-9cdc-7b0fb7338b03'),
    ('Danemark', 'DK', '810c13b9-f7f1-46b9-9cdc-7b0fb7338b03')
) AS missing(name, code, continent_id)
WHERE NOT EXISTS (SELECT 1 FROM countries WHERE code = missing.code);

-- =====================================================
-- PARTIE 2 : Import des villes (version robuste corrigée)
-- =====================================================

INSERT INTO cities (name, country_id)
SELECT v.name, c.id
FROM (VALUES
        
        -- =====================================================
        -- AFRIQUE DE L'OUEST
        -- =====================================================
        
        -- BÉNIN (BJ) - ENRICHIE
        ('Cotonou', 'BJ'),
        ('Porto-Novo', 'BJ'),
        ('Parakou', 'BJ'),
        ('Djougou', 'BJ'),
        ('Bohicon', 'BJ'),
        ('Kandi', 'BJ'),
        ('Lokossa', 'BJ'),
        ('Ouidah', 'BJ'),
        ('Abomey', 'BJ'),
        ('Natitingou', 'BJ'),
        ('Savé', 'BJ'),
        ('Nikki', 'BJ'),
        ('Pobè', 'BJ'),
        ('Kétou', 'BJ'),
        ('Banikoara', 'BJ'),
        ('Malanville', 'BJ'),
        ('Tchaourou', 'BJ'),
        ('Dogbo', 'BJ'),
        ('Comè', 'BJ'),
        ('Bassila', 'BJ'),
        ('Bembèréké', 'BJ'),
        
        -- SÉNÉGAL (SN) - ENRICHIE
        ('Dakar', 'SN'),
        ('Saint-Louis', 'SN'),
        ('Thiès', 'SN'),
        ('Kaolack', 'SN'),
        ('Ziguinchor', 'SN'),
        ('Mbour', 'SN'),
        ('Touba', 'SN'),
        ('Diourbel', 'SN'),
        ('Tambacounda', 'SN'),
        ('Kolda', 'SN'),
        ('Fatick', 'SN'),
        ('Kaffrine', 'SN'),
        ('Kédougou', 'SN'),
        ('Sédhiou', 'SN'),
        ('Matam', 'SN'),
        ('Louga', 'SN'),
        ('Bignona', 'SN'),
        ('Vélingara', 'SN'),
        ('Dagana', 'SN'),
        ('Nioro', 'SN'),
        
        -- CÔTE D'IVOIRE (CI) - ENRICHIE
        ('Abidjan', 'CI'),
        ('Bouaké', 'CI'),
        ('Yamoussoukro', 'CI'),
        ('Daloa', 'CI'),
        ('Korhogo', 'CI'),
        ('San-Pédro', 'CI'),
        ('Man', 'CI'),
        ('Gagnoa', 'CI'),
        ('Abengourou', 'CI'),
        ('Divo', 'CI'),
        ('Bondoukou', 'CI'),
        ('Soubré', 'CI'),
        ('Séguéla', 'CI'),
        ('Agboville', 'CI'),
        ('Odienné', 'CI'),
        ('Touba', 'CI'),
        ('Duekoué', 'CI'),
        ('Aboisso', 'CI'),
        ('Grand-Bassam', 'CI'),
        ('Bingerville', 'CI'),
        
        -- GHANA (GH) - ENRICHIE
        ('Accra', 'GH'),
        ('Kumasi', 'GH'),
        ('Tamale', 'GH'),
        ('Sekondi-Takoradi', 'GH'),
        ('Cape Coast', 'GH'),
        ('Koforidua', 'GH'),
        ('Sunyani', 'GH'),
        ('Ho', 'GH'),
        ('Bolgatanga', 'GH'),
        ('Tema', 'GH'),
        ('Obuasi', 'GH'),
        ('Techiman', 'GH'),
        ('Wa', 'GH'),
        ('Nkawkaw', 'GH'),
        ('Ejura', 'GH'),
        
        -- TOGO (TG) - NOUVEAU
        ('Lomé', 'TG'),
        ('Sokodé', 'TG'),
        ('Kara', 'TG'),
        ('Atakpamé', 'TG'),
        ('Palimé', 'TG'),
        ('Bassar', 'TG'),
        ('Tsévié', 'TG'),
        ('Aného', 'TG'),
        ('Mango', 'TG'),
        ('Dapaong', 'TG'),
        ('Tchamba', 'TG'),
        ('Niamtougou', 'TG'),
        ('Bafilo', 'TG'),
        ('Notse', 'TG'),
        ('Sotouboua', 'TG'),
        
        -- MALI (ML) - NOUVEAU
        ('Bamako', 'ML'),
        ('Sikasso', 'ML'),
        ('Mopti', 'ML'),
        ('Ségou', 'ML'),
        ('Koutiala', 'ML'),
        ('Kayes', 'ML'),
        ('Gao', 'ML'),
        ('Timbuktu', 'ML'),
        ('San', 'ML'),
        ('Kati', 'ML'),
        ('Kolondiéba', 'ML'),
        ('Bougouni', 'ML'),
        ('Markala', 'ML'),
        ('Niono', 'ML'),
        ('Koulikoro', 'ML'),
        
        -- BURKINA FASO (BF) - NOUVEAU
        ('Ouagadougou', 'BF'),
        ('Bobo-Dioulasso', 'BF'),
        ('Koudougou', 'BF'),
        ('Ouahigouya', 'BF'),
        ('Banfora', 'BF'),
        ('Dédougou', 'BF'),
        ('Kaya', 'BF'),
        ('Tenkodogo', 'BF'),
        ('Fada N''Gourma', 'BF'),
        ('Houndé', 'BF'),
        ('Ziniaré', 'BF'),
        ('Pô', 'BF'),
        ('Yako', 'BF'),
        ('Léo', 'BF'),
        ('Nouna', 'BF'),
        
        -- NIGER (NE) - NOUVEAU
        ('Niamey', 'NE'),
        ('Zinder', 'NE'),
        ('Maradi', 'NE'),
        ('Agadez', 'NE'),
        ('Tahoua', 'NE'),
        ('Dosso', 'NE'),
        ('Birni N''Konni', 'NE'),
        ('Gaya', 'NE'),
        ('Téra', 'NE'),
        ('Ayorou', 'NE'),
        ('Magaria', 'NE'),
        ('Diffa', 'NE'),
        ('Tillabéri', 'NE'),
        ('Madaoua', 'NE'),
        ('Illéla', 'NE'),
        
        -- GUINÉE (GN) - NOUVEAU
        ('Conakry', 'GN'),
        ('Nzérékoré', 'GN'),
        ('Kankan', 'GN'),
        ('Kindia', 'GN'),
        ('Labé', 'GN'),
        ('Mamou', 'GN'),
        ('Boké', 'GN'),
        ('Faranah', 'GN'),
        ('Kissidougou', 'GN'),
        ('Guéckédou', 'GN'),
        ('Siguiri', 'GN'),
        ('Macenta', 'GN'),
        ('Télimélé', 'GN'),
        ('Tougué', 'GN'),
        ('Dalaba', 'GN'),
        
        -- SIERRA LEONE (SL) - NOUVEAU
        ('Freetown', 'SL'),
        ('Bo', 'SL'),
        ('Kenema', 'SL'),
        ('Makeni', 'SL'),
        ('Koidu Town', 'SL'),
        ('Lunsar', 'SL'),
        ('Port Loko', 'SL'),
        ('Kabala', 'SL'),
        ('Waterloo', 'SL'),
        ('Magburaka', 'SL'),
        
        -- LIBÉRIA (LR) - NOUVEAU
        ('Monrovia', 'LR'),
        ('Gbarnga', 'LR'),
        ('Buchanan', 'LR'),
        ('Kakata', 'LR'),
        ('Harper', 'LR'),
        ('Zwedru', 'LR'),
        ('Voinjama', 'LR'),
        ('Greenville', 'LR'),
        ('Robertsport', 'LR'),
        ('Sanniquellie', 'LR'),
        
        -- MAURITANIE (MR) - NOUVEAU
        ('Nouakchott', 'MR'),
        ('Nouadhibou', 'MR'),
        ('Rosso', 'MR'),
        ('Kiffa', 'MR'),
        ('Zouérat', 'MR'),
        ('Kaédi', 'MR'),
        ('Boutilimit', 'MR'),
        ('Atar', 'MR'),
        ('Sélibaby', 'MR'),
        ('Aleg', 'MR'),
        
        -- GAMBIE (GM) - NOUVEAU
        ('Banjul', 'GM'),
        ('Serrekunda', 'GM'),
        ('Brikama', 'GM'),
        ('Bakau', 'GM'),
        ('Farafenni', 'GM'),
        ('Lamin', 'GM'),
        ('Sukuta', 'GM'),
        ('Basse Santa Su', 'GM'),
        ('Kerewan', 'GM'),
        ('Mansa Konko', 'GM'),
        
        -- GUINÉE-BISSAU (GW) - NOUVEAU
        ('Bissau', 'GW'),
        ('Bafatá', 'GW'),
        ('Gabú', 'GW'),
        ('Bissorã', 'GW'),
        ('Bolama', 'GW'),
        ('Cacheu', 'GW'),
        ('Buba', 'GW'),
        ('Fulacunda', 'GW'),
        ('Quebo', 'GW'),
        ('Catió', 'GW'),
        
        -- CAP-VERT (CV) - NOUVEAU
        ('Praia', 'CV'),
        ('Mindelo', 'CV'),
        ('Santa Maria', 'CV'),
        ('Assomada', 'CV'),
        ('São Filipe', 'CV'),
        ('Espargos', 'CV'),
        ('Tarrafal', 'CV'),
        ('Porto Novo', 'CV'),
        ('Ribeira Grande', 'CV'),
        ('Pedra Badejo', 'CV'),
        
        -- =====================================================
        -- AFRIQUE CENTRALE
        -- =====================================================
        
        -- CAMEROUN (CM) - ENRICHIE
        ('Yaoundé', 'CM'),
        ('Douala', 'CM'),
        ('Garoua', 'CM'),
        ('Bamenda', 'CM'),
        ('Maroua', 'CM'),
        ('Ngaoundéré', 'CM'),
        ('Bafoussam', 'CM'),
        ('Bertoua', 'CM'),
        ('Edéa', 'CM'),
        ('Kousséri', 'CM'),
        ('Ebolowa', 'CM'),
        ('Foumban', 'CM'),
        ('Limbé', 'CM'),
        ('Kumba', 'CM'),
        ('Buea', 'CM'),
        ('Mokolo', 'CM'),
        ('Yagoua', 'CM'),
        ('Abong-Mbang', 'CM'),
        ('Sangmélima', 'CM'),
        ('Mbouda', 'CM'),
        
        -- RDC (CD) - ENRICHIE
        ('Kinshasa', 'CD'),
        ('Lubumbashi', 'CD'),
        ('Mbuji-Mayi', 'CD'),
        ('Kisangani', 'CD'),
        ('Kananga', 'CD'),
        ('Goma', 'CD'),
        ('Bukavu', 'CD'),
        ('Mwene-Ditu', 'CD'),
        ('Kikwit', 'CD'),
        ('Mbandaka', 'CD'),
        ('Matadi', 'CD'),
        ('Uvira', 'CD'),
        ('Butembo', 'CD'),
        ('Likasi', 'CD'),
        ('Kolwezi', 'CD'),
        ('Tshikapa', 'CD'),
        ('Boma', 'CD'),
        ('Bunia', 'CD'),
        ('Bumba', 'CD'),
        ('Isiro', 'CD'),
        
        -- GABON (GA) - NOUVEAU
        ('Libreville', 'GA'),
        ('Port-Gentil', 'GA'),
        ('Franceville', 'GA'),
        ('Oyem', 'GA'),
        ('Moanda', 'GA'),
        ('Mouila', 'GA'),
        ('Lambaréné', 'GA'),
        ('Tchibanga', 'GA'),
        ('Koulamoutou', 'GA'),
        ('Makokou', 'GA'),
        ('Bitam', 'GA'),
        ('Ntoum', 'GA'),
        ('Mounana', 'GA'),
        ('Lastoursville', 'GA'),
        ('Mayumba', 'GA'),
        
        -- RÉPUBLIQUE DU CONGO (CG) - NOUVEAU
        ('Brazzaville', 'CG'),
        ('Pointe-Noire', 'CG'),
        ('Dolisie', 'CG'),
        ('Nkayi', 'CG'),
        ('Kindamba', 'CG'),
        ('Impfondo', 'CG'),
        ('Ouésso', 'CG'),
        ('Madingou', 'CG'),
        ('Mossendjo', 'CG'),
        ('Owando', 'CG'),
        ('Sibiti', 'CG'),
        ('Gamboma', 'CG'),
        ('Kinkala', 'CG'),
        ('Mbandza-Ndounga', 'CG'),
        ('Djambala', 'CG'),
        
        -- RÉPUBLIQUE CENTRAFRICAINE (CF) - NOUVEAU
        ('Bangui', 'CF'),
        ('Bimbo', 'CF'),
        ('Berbérati', 'CF'),
        ('Carnot', 'CF'),
        ('Bambari', 'CF'),
        ('Bossangoa', 'CF'),
        ('Bria', 'CF'),
        ('Kaga-Bandoro', 'CF'),
        ('Mbaïki', 'CF'),
        ('Boali', 'CF'),
        ('Nola', 'CF'),
        ('Bouar', 'CF'),
        ('Batangafo', 'CF'),
        ('Sibut', 'CF'),
        ('Paoua', 'CF'),
        
        -- TCHAD (TD) - NOUVEAU
        ('N''Djamena', 'TD'),
        ('Moundou', 'TD'),
        ('Sarh', 'TD'),
        ('Abéché', 'TD'),
        ('Kélo', 'TD'),
        ('Koumra', 'TD'),
        ('Pala', 'TD'),
        ('Am Timan', 'TD'),
        ('Bongor', 'TD'),
        ('Mongo', 'TD'),
        ('Doba', 'TD'),
        ('Ati', 'TD'),
        ('Lai', 'TD'),
        ('Oum Hadjer', 'TD'),
        ('Bitkine', 'TD'),
        
        -- GUINÉE ÉQUATORIALE (GQ) - NOUVEAU
        ('Malabo', 'GQ'),
        ('Bata', 'GQ'),
        ('Ebebiyín', 'GQ'),
        ('Luba', 'GQ'),
        ('Evinayong', 'GQ'),
        ('Mongomo', 'GQ'),
        ('Mikomeseng', 'GQ'),
        ('Aconibe', 'GQ'),
        ('Nsok', 'GQ'),
        ('Rio Campo', 'GQ'),
        
        -- =====================================================
        -- AFRIQUE DE L'EST
        -- =====================================================
        
        -- KENYA (KE) - ENRICHIE
        ('Nairobi', 'KE'),
        ('Mombasa', 'KE'),
        ('Kisumu', 'KE'),
        ('Nakuru', 'KE'),
        ('Eldoret', 'KE'),
        ('Thika', 'KE'),
        ('Malindi', 'KE'),
        ('Kitale', 'KE'),
        ('Garissa', 'KE'),
        ('Kakamega', 'KE'),
        ('Machakos', 'KE'),
        ('Meru', 'KE'),
        ('Nyeri', 'KE'),
        ('Kilifi', 'KE'),
        ('Wajir', 'KE'),
        ('Migori', 'KE'),
        ('Busia', 'KE'),
        ('Homa Bay', 'KE'),
        ('Embu', 'KE'),
        ('Isiolo', 'KE'),
        
        -- TANZANIE (TZ) - NOUVEAU
        ('Dar es Salaam', 'TZ'),
        ('Dodoma', 'TZ'),
        ('Arusha', 'TZ'),
        ('Mwanza', 'TZ'),
        ('Mbeya', 'TZ'),
        ('Zanzibar', 'TZ'),
        ('Tanga', 'TZ'),
        ('Morogoro', 'TZ'),
        ('Kigoma', 'TZ'),
        ('Moshi', 'TZ'),
        ('Tabora', 'TZ'),
        ('Songea', 'TZ'),
        ('Musoma', 'TZ'),
        ('Iringa', 'TZ'),
        ('Katavi', 'TZ'),
        ('Shinyanga', 'TZ'),
        ('Lindi', 'TZ'),
        ('Simiyu', 'TZ'),
        ('Njombe', 'TZ'),
        ('Geita', 'TZ'),
        
        -- OUGANDA (UG) - NOUVEAU
        ('Kampala', 'UG'),
        ('Gulu', 'UG'),
        ('Lira', 'UG'),
        ('Jinja', 'UG'),
        ('Mbarara', 'UG'),
        ('Entebbe', 'UG'),
        ('Mbale', 'UG'),
        ('Masaka', 'UG'),
        ('Kasese', 'UG'),
        ('Soroti', 'UG'),
        ('Fort Portal', 'UG'),
        ('Arua', 'UG'),
        ('Tororo', 'UG'),
        ('Busia', 'UG'),
        ('Mukono', 'UG'),
        ('Njeru', 'UG'),
        ('Kabale', 'UG'),
        ('Kumi', 'UG'),
        ('Kitgum', 'UG'),
        ('Moroto', 'UG'),
        
        -- RWANDA (RW) - NOUVEAU
        ('Kigali', 'RW'),
        ('Butare', 'RW'),
        ('Gisenyi', 'RW'),
        ('Ruhengeri', 'RW'),
        ('Gitarama', 'RW'),
        ('Byumba', 'RW'),
        ('Cyangugu', 'RW'),
        ('Kibungo', 'RW'),
        ('Kibuye', 'RW'),
        ('Rwamagana', 'RW'),
        
        -- BURUNDI (BI) - NOUVEAU
        ('Bujumbura', 'BI'),
        ('Gitega', 'BI'),
        ('Ngozi', 'BI'),
        ('Rumonge', 'BI'),
        ('Muyinga', 'BI'),
        ('Cibitoke', 'BI'),
        ('Kayanza', 'BI'),
        ('Ruyigi', 'BI'),
        ('Makamba', 'BI'),
        ('Bururi', 'BI'),
        
        -- SOMALIE (SO) - NOUVEAU
        ('Mogadishu', 'SO'),
        ('Hargeisa', 'SO'),
        ('Kismayo', 'SO'),
        ('Baidoa', 'SO'),
        ('Bosaso', 'SO'),
        ('Galkayo', 'SO'),
        ('Berbera', 'SO'),
        ('Beledweyne', 'SO'),
        ('Garowe', 'SO'),
        ('Burao', 'SO'),
        
        -- DJIBOUTI (DJ) - NOUVEAU
        ('Djibouti', 'DJ'),
        ('Ali Sabieh', 'DJ'),
        ('Dikhil', 'DJ'),
        ('Tadjoura', 'DJ'),
        ('Obock', 'DJ'),
        ('Arta', 'DJ'),
        ('Randa', 'DJ'),
        ('Holhol', 'DJ'),
        ('Loyada', 'DJ'),
        ('Yoboki', 'DJ'),
        
        -- ÉRYTHRÉE (ER) - NOUVEAU
        ('Asmara', 'ER'),
        ('Keren', 'ER'),
        ('Massawa', 'ER'),
        ('Assab', 'ER'),
        ('Mendefera', 'ER'),
        ('Barentu', 'ER'),
        ('Tessenei', 'ER'),
        ('Adi Quala', 'ER'),
        ('Senafe', 'ER'),
        ('Dekemhare', 'ER'),
        
        -- =====================================================
        -- AFRIQUE AUSTRALE
        -- =====================================================
        
        -- AFRIQUE DU SUD (ZA) - ENRICHIE
        ('Johannesburg', 'ZA'),
        ('Cape Town', 'ZA'),
        ('Durban', 'ZA'),
        ('Pretoria', 'ZA'),
        ('Port Elizabeth', 'ZA'),
        ('Bloemfontein', 'ZA'),
        ('East London', 'ZA'),
        ('Kimberley', 'ZA'),
        ('Polokwane', 'ZA'),
        ('Nelspruit', 'ZA'),
        ('Pietermaritzburg', 'ZA'),
        ('Rustenburg', 'ZA'),
        ('Middelburg', 'ZA'),
        ('Vereeniging', 'ZA'),
        ('Witbank', 'ZA'),
        ('Botshabelo', 'ZA'),
        ('Boksburg', 'ZA'),
        ('George', 'ZA'),
        ('Krugersdorp', 'ZA'),
        ('Brakpan', 'ZA'),
        
        -- ZAMBIE (ZM) - NOUVEAU
        ('Lusaka', 'ZM'),
        ('Kitwe', 'ZM'),
        ('Ndola', 'ZM'),
        ('Kabwe', 'ZM'),
        ('Chingola', 'ZM'),
        ('Mufulira', 'ZM'),
        ('Livingstone', 'ZM'),
        ('Luanshya', 'ZM'),
        ('Chililabombwe', 'ZM'),
        ('Mongu', 'ZM'),
        ('Kafue', 'ZM'),
        ('Choma', 'ZM'),
        ('Kasama', 'ZM'),
        ('Solwezi', 'ZM'),
        ('Chipata', 'ZM'),
        
        -- ZIMBABWE (ZW) - NOUVEAU
        ('Harare', 'ZW'),
        ('Bulawayo', 'ZW'),
        ('Mutare', 'ZW'),
        ('Gweru', 'ZW'),
        ('Kwekwe', 'ZW'),
        ('Masvingo', 'ZW'),
        ('Chitungwiza', 'ZW'),
        ('Epworth', 'ZW'),
        ('Marondera', 'ZW'),
        ('Zvishavane', 'ZW'),
        
        -- MOZAMBIQUE (MZ) - NOUVEAU
        ('Maputo', 'MZ'),
        ('Matola', 'MZ'),
        ('Beira', 'MZ'),
        ('Nampula', 'MZ'),
        ('Chimoio', 'MZ'),
        ('Quelimane', 'MZ'),
        ('Tete', 'MZ'),
        ('Xai-Xai', 'MZ'),
        ('Maxixe', 'MZ'),
        ('Lichinga', 'MZ'),
        ('Pemba', 'MZ'),
        ('Gurúè', 'MZ'),
        ('Manica', 'MZ'),
        ('Inhambane', 'MZ'),
        ('Mocuba', 'MZ'),
        
        -- MALAWI (MW) - NOUVEAU
        ('Lilongwe', 'MW'),
        ('Blantyre', 'MW'),
        ('Mzuzu', 'MW'),
        ('Zomba', 'MW'),
        ('Kasungu', 'MW'),
        ('Mangochi', 'MW'),
        ('Karonga', 'MW'),
        ('Salima', 'MW'),
        ('Nkhotakota', 'MW'),
        ('Thyolo', 'MW'),
        
        -- NAMIBIE (NA) - NOUVEAU
        ('Windhoek', 'NA'),
        ('Walvis Bay', 'NA'),
        ('Swakopmund', 'NA'),
        ('Ondangwa', 'NA'),
        ('Rundu', 'NA'),
        ('Oshakati', 'NA'),
        ('Otjiwarongo', 'NA'),
        ('Katima Mulilo', 'NA'),
        ('Gobabis', 'NA'),
        ('Keetmanshoop', 'NA'),
        
        -- BOTSWANA (BW) - NOUVEAU
        ('Gaborone', 'BW'),
        ('Francistown', 'BW'),
        ('Molepolole', 'BW'),
        ('Maun', 'BW'),
        ('Serowe', 'BW'),
        ('Kanye', 'BW'),
        ('Mahalapye', 'BW'),
        ('Lobatse', 'BW'),
        ('Palapye', 'BW'),
        ('Tshabong', 'BW'),
        
        -- ANGOLA (AO) - NOUVEAU
        ('Luanda', 'AO'),
        ('Huambo', 'AO'),
        ('Benguela', 'AO'),
        ('Lubango', 'AO'),
        ('Cabinda', 'AO'),
        ('Malanje', 'AO'),
        ('Kuito', 'AO'),
        ('Lobito', 'AO'),
        ('Saurimo', 'AO'),
        ('Mbanza Congo', 'AO'),
        
        -- =====================================================
        -- AFRIQUE DU NORD
        -- =====================================================
        
        -- MAROC (MA) - ENRICHIE
        ('Casablanca', 'MA'),
        ('Rabat', 'MA'),
        ('Marrakech', 'MA'),
        ('Fès', 'MA'),
        ('Tanger', 'MA'),
        ('Agadir', 'MA'),
        ('Meknès', 'MA'),
        ('Oujda', 'MA'),
        ('Tétouan', 'MA'),
        ('Kénitra', 'MA'),
        ('Salé', 'MA'),
        ('Nador', 'MA'),
        ('Safi', 'MA'),
        ('El Jadida', 'MA'),
        ('Beni Mellal', 'MA'),
        ('Taza', 'MA'),
        ('Settat', 'MA'),
        ('Larache', 'MA'),
        ('Khouribga', 'MA'),
        ('Ouarzazate', 'MA'),
        
        -- ALGÉRIE (DZ) - NOUVEAU
        ('Alger', 'DZ'),
        ('Oran', 'DZ'),
        ('Constantine', 'DZ'),
        ('Annaba', 'DZ'),
        ('Blida', 'DZ'),
        ('Sétif', 'DZ'),
        ('Tizi Ouzou', 'DZ'),
        ('Béjaïa', 'DZ'),
        ('Skikda', 'DZ'),
        ('Tlemcen', 'DZ'),
        ('Biskra', 'DZ'),
        ('Tébessa', 'DZ'),
        ('Batna', 'DZ'),
        ('Djelfa', 'DZ'),
        ('Sidi Bel Abbès', 'DZ'),
        
        -- TUNISIE (TN) - NOUVEAU
        ('Tunis', 'TN'),
        ('Sfax', 'TN'),
        ('Sousse', 'TN'),
        ('Kairouan', 'TN'),
        ('Bizerte', 'TN'),
        ('Gabès', 'TN'),
        ('Ariana', 'TN'),
        ('Gafsa', 'TN'),
        ('Monastir', 'TN'),
        ('La Marsa', 'TN'),
        
        -- LIBYE (LY) - NOUVEAU
        ('Tripoli', 'LY'),
        ('Benghazi', 'LY'),
        ('Misrata', 'LY'),
        ('Bayda', 'LY'),
        ('Zawiya', 'LY'),
        ('Zliten', 'LY'),
        ('Sirte', 'LY'),
        ('Tobruk', 'LY'),
        ('Sabha', 'LY'),
        ('Derna', 'LY'),
        
        -- ÉGYPTE (EG) - NOUVEAU
        ('Cairo', 'EG'),
        ('Alexandria', 'EG'),
        ('Giza', 'EG'),
        ('Luxor', 'EG'),
        ('Aswan', 'EG'),
        ('Port Said', 'EG'),
        ('Suez', 'EG'),
        ('Mansoura', 'EG'),
        ('Tanta', 'EG'),
        ('Zagazig', 'EG'),
        ('Ismailia', 'EG'),
        ('Faiyum', 'EG'),
        ('Asyut', 'EG'),
        ('Sohag', 'EG'),
        ('Beni Suef', 'EG'),
        
        -- SOUDAN (SD) - NOUVEAU
        ('Khartoum', 'SD'),
        ('Omdurman', 'SD'),
        ('Port Sudan', 'SD'),
        ('Kassala', 'SD'),
        ('Nyala', 'SD'),
        ('El Obeid', 'SD'),
        ('Wad Madani', 'SD'),
        ('El Fasher', 'SD'),
        ('Gedaref', 'SD'),
        ('Geneina', 'SD'),
        
        -- =====================================================
        -- AUTRES PAYS (Europe, Amériques, Asie, Océanie)
        -- =====================================================
        
        -- FRANCE (FR)
        ('Paris', 'FR'),
        ('Marseille', 'FR'),
        ('Lyon', 'FR'),
        ('Toulouse', 'FR'),
        ('Nice', 'FR'),
        ('Nantes', 'FR'),
        ('Strasbourg', 'FR'),
        ('Montpellier', 'FR'),
        ('Bordeaux', 'FR'),
        ('Lille', 'FR'),
        ('Rennes', 'FR'),
        ('Reims', 'FR'),
        ('Saint-Étienne', 'FR'),
        ('Toulon', 'FR'),
        ('Grenoble', 'FR'),
        
        -- ÉTATS-UNIS (US)
        ('New York', 'US'),
        ('Los Angeles', 'US'),
        ('Chicago', 'US'),
        ('Houston', 'US'),
        ('Phoenix', 'US'),
        ('Philadelphia', 'US'),
        ('San Antonio', 'US'),
        ('San Diego', 'US'),
        ('Dallas', 'US'),
        ('Austin', 'US'),
        ('Boston', 'US'),
        ('Seattle', 'US'),
        ('Denver', 'US'),
        ('Washington', 'US'),
        ('San Francisco', 'US'),
        
        -- CANADA (CA)
        ('Toronto', 'CA'),
        ('Montreal', 'CA'),
        ('Vancouver', 'CA'),
        ('Calgary', 'CA'),
        ('Edmonton', 'CA'),
        ('Ottawa', 'CA'),
        ('Quebec', 'CA'),
        ('Winnipeg', 'CA'),
        ('Hamilton', 'CA'),
        ('Kitchener', 'CA'),
        
        -- ROYAUME-UNI (GB)
        ('London', 'GB'),
        ('Birmingham', 'GB'),
        ('Manchester', 'GB'),
        ('Glasgow', 'GB'),
        ('Liverpool', 'GB'),
        ('Bristol', 'GB'),
        ('Sheffield', 'GB'),
        ('Leeds', 'GB'),
        ('Edinburgh', 'GB'),
        ('Newcastle', 'GB'),
        
        -- ALLEMAGNE (DE)
        ('Berlin', 'DE'),
        ('Hamburg', 'DE'),
        ('Munich', 'DE'),
        ('Cologne', 'DE'),
        ('Frankfurt', 'DE'),
        ('Stuttgart', 'DE'),
        ('Düsseldorf', 'DE'),
        ('Leipzig', 'DE'),
        ('Dresden', 'DE'),
        ('Hanover', 'DE'),
        
        -- ITALIE (IT)
        ('Rome', 'IT'),
        ('Milan', 'IT'),
        ('Naples', 'IT'),
        ('Turin', 'IT'),
        ('Palermo', 'IT'),
        ('Genoa', 'IT'),
        ('Bologna', 'IT'),
        ('Florence', 'IT'),
        ('Venice', 'IT'),
        ('Verona', 'IT'),
        
        -- ESPAGNE (ES)
        ('Madrid', 'ES'),
        ('Barcelona', 'ES'),
        ('Valencia', 'ES'),
        ('Seville', 'ES'),
        ('Zaragoza', 'ES'),
        ('Málaga', 'ES'),
        ('Murcia', 'ES'),
        ('Palma', 'ES'),
        ('Las Palmas', 'ES'),
        ('Bilbao', 'ES'),
        
        -- SUISSE (CH)
        ('Zurich', 'CH'),
        ('Geneva', 'CH'),
        ('Basel', 'CH'),
        ('Bern', 'CH'),
        ('Lausanne', 'CH'),
        ('Lucerne', 'CH'),
        ('St. Gallen', 'CH'),
        ('Lugano', 'CH'),
        ('Biel', 'CH'),
        ('Thun', 'CH'),
        
        -- BELGIQUE (BE)
        ('Brussels', 'BE'),
        ('Antwerp', 'BE'),
        ('Ghent', 'BE'),
        ('Charleroi', 'BE'),
        ('Liège', 'BE'),
        ('Bruges', 'BE'),
        ('Namur', 'BE'),
        ('Leuven', 'BE'),
        ('Mons', 'BE'),
        ('Mechelen', 'BE'),
        
        -- PAYS-BAS (NL)
        ('Amsterdam', 'NL'),
        ('Rotterdam', 'NL'),
        ('The Hague', 'NL'),
        ('Utrecht', 'NL'),
        ('Eindhoven', 'NL'),
        ('Groningen', 'NL'),
        ('Tilburg', 'NL'),
        ('Almere', 'NL'),
        ('Breda', 'NL'),
        ('Nijmegen', 'NL'),
        
        -- PORTUGAL (PT)
        ('Lisbon', 'PT'),
        ('Porto', 'PT'),
        ('Vila Nova de Gaia', 'PT'),
        ('Amadora', 'PT'),
        ('Braga', 'PT'),
        ('Coimbra', 'PT'),
        ('Funchal', 'PT'),
        ('Setúbal', 'PT'),
        ('Almada', 'PT'),
        ('Agualva-Cacém', 'PT'),
        
        -- BRÉSIL (BR)
        ('São Paulo', 'BR'),
        ('Rio de Janeiro', 'BR'),
        ('Brasília', 'BR'),
        ('Salvador', 'BR'),
        ('Fortaleza', 'BR'),
        ('Belo Horizonte', 'BR'),
        ('Manaus', 'BR'),
        ('Curitiba', 'BR'),
        ('Recife', 'BR'),
        ('Porto Alegre', 'BR'),
        
        -- NIGÉRIA (NG)
        ('Lagos', 'NG'),
        ('Kano', 'NG'),
        ('Abuja', 'NG'),
        ('Ibadan', 'NG'),
        ('Port Harcourt', 'NG'),
        ('Benin City', 'NG'),
        ('Maiduguri', 'NG'),
        ('Zaria', 'NG'),
        ('Aba', 'NG'),
        ('Jos', 'NG'),
        
        -- CHINE (CN)
        ('Beijing', 'CN'),
        ('Shanghai', 'CN'),
        ('Guangzhou', 'CN'),
        ('Shenzhen', 'CN'),
        ('Chengdu', 'CN'),
        ('Wuhan', 'CN'),
        ('Xi''an', 'CN'),
        ('Nanjing', 'CN'),
        ('Hangzhou', 'CN'),
        ('Chongqing', 'CN'),
        
        -- INDE (IN)
        ('Mumbai', 'IN'),
        ('Delhi', 'IN'),
        ('Bangalore', 'IN'),
        ('Hyderabad', 'IN'),
        ('Ahmedabad', 'IN'),
        ('Chennai', 'IN'),
        ('Kolkata', 'IN'),
        ('Pune', 'IN'),
        ('Jaipur', 'IN'),
        ('Lucknow', 'IN'),
        
        -- JAPON (JP)
        ('Tokyo', 'JP'),
        ('Yokohama', 'JP'),
        ('Osaka', 'JP'),
        ('Nagoya', 'JP'),
        ('Sapporo', 'JP'),
        ('Fukuoka', 'JP'),
        ('Kobe', 'JP'),
        ('Kyoto', 'JP'),
        ('Kawasaki', 'JP'),
        ('Saitama', 'JP'),
        
        -- AUSTRALIE (AU)
        ('Sydney', 'AU'),
        ('Melbourne', 'AU'),
        ('Brisbane', 'AU'),
        ('Perth', 'AU'),
        ('Adelaide', 'AU'),
        ('Gold Coast', 'AU'),
        ('Canberra', 'AU'),
        ('Newcastle', 'AU'),
        ('Wollongong', 'AU'),
        ('Hobart', 'AU'),
        
        -- RUSSIE (RU)
        ('Moscow', 'RU'),
        ('Saint Petersburg', 'RU'),
        ('Novosibirsk', 'RU'),
        ('Yekaterinburg', 'RU'),
        ('Nizhny Novgorod', 'RU'),
        ('Kazan', 'RU'),
        ('Chelyabinsk', 'RU'),
        ('Omsk', 'RU'),
        ('Samara', 'RU'),
        ('Rostov-on-Don', 'RU'),
        ('Ufa', 'RU'),
        ('Krasnoyarsk', 'RU'),
        ('Perm', 'RU'),
        ('Voronezh', 'RU'),
        ('Volgograd', 'RU'),
        
        -- SUÈDE (SE)
        ('Stockholm', 'SE'),
        ('Gothenburg', 'SE'),
        ('Malmö', 'SE'),
        ('Uppsala', 'SE'),
        ('Västerås', 'SE'),
        ('Örebro', 'SE'),
        ('Linköping', 'SE'),
        ('Helsingborg', 'SE'),
        ('Jönköping', 'SE'),
        ('Norrköping', 'SE'),
        
        -- NORVÈGE (NO)
        ('Oslo', 'NO'),
        ('Bergen', 'NO'),
        ('Trondheim', 'NO'),
        ('Stavanger', 'NO'),
        ('Drammen', 'NO'),
        ('Fredrikstad', 'NO'),
        ('Kristiansand', 'NO'),
        ('Sandnes', 'NO'),
        ('Tromsø', 'NO'),
        ('Ålesund', 'NO'),
        
        -- DANEMARK (DK)
        ('Copenhagen', 'DK'),
        ('Aarhus', 'DK'),
        ('Odense', 'DK'),
        ('Aalborg', 'DK'),
        ('Esbjerg', 'DK'),
        ('Randers', 'DK'),
        ('Kolding', 'DK'),
        ('Horsens', 'DK'),
        ('Vejle', 'DK'),
        ('Roskilde', 'DK')
        
    ) AS v(name, code)
    JOIN countries c ON c.code = v.code
WHERE NOT EXISTS (
    SELECT 1 FROM cities ci 
    WHERE ci.name = v.name AND ci.country_id = c.id
);

-- =====================================================
-- PARTIE 3 : Index pour performances
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_cities_country_id ON public.cities(country_id);
CREATE INDEX IF NOT EXISTS idx_cities_name ON public.cities(name);

-- =====================================================
-- PARTIE 4 : Vérification
-- =====================================================

-- Compter les villes par pays
SELECT 
    co.name as country_name,
    co.code,
    COUNT(ci.id) as cities_count
FROM countries co
LEFT JOIN cities ci ON ci.country_id = co.id
WHERE co.code IN ('BJ', 'SN', 'CI', 'GH', 'TG', 'ML', 'BF', 'NE', 'GN', 'SL', 'LR', 'MR', 'GM', 'GW', 'CV', 'CM', 'CD', 'GA', 'CG', 'CF', 'TD', 'GQ', 'KE', 'TZ', 'UG', 'RW', 'BI', 'SO', 'ZA', 'ZM', 'ZW', 'MZ', 'MW', 'NA', 'BW', 'AO', 'MA', 'DZ', 'TN', 'LY', 'EG', 'SD', 'RU')
GROUP BY co.name, co.code
ORDER BY co.name;

-- =====================================================
-- FIN DE LA MIGRATION
-- =====================================================