-- =====================================================
-- MIGRATION : Import des continents et pays
-- Date : 27/05/2026
-- Source : Données GeoNames / Natural Earth
-- =====================================================

-- 1. Nettoyer les tables existantes (optionnel)
TRUNCATE TABLE cities CASCADE;
TRUNCATE TABLE countries CASCADE;
TRUNCATE TABLE continents CASCADE;

-- 2. Insérer les continents
INSERT INTO continents (name, code) VALUES
('Afrique', 'AF'),
('Europe', 'EU'),
('Amérique du Nord', 'NA'),
('Amérique du Sud', 'SA'),
('Asie', 'AS'),
('Océanie', 'OC'),
('Antarctique', 'AN')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- 3. Insérer les pays (250 pays avec codes ISO)
INSERT INTO countries (name, code, continent_id) VALUES
-- Afrique (AF)
('Algérie', 'DZ', (SELECT id FROM continents WHERE code = 'AF')),
('Angola', 'AO', (SELECT id FROM continents WHERE code = 'AF')),
('Bénin', 'BJ', (SELECT id FROM continents WHERE code = 'AF')),
('Botswana', 'BW', (SELECT id FROM continents WHERE code = 'AF')),
('Burkina Faso', 'BF', (SELECT id FROM continents WHERE code = 'AF')),
('Burundi', 'BI', (SELECT id FROM continents WHERE code = 'AF')),
('Cameroun', 'CM', (SELECT id FROM continents WHERE code = 'AF')),
('Cap-Vert', 'CV', (SELECT id FROM continents WHERE code = 'AF')),
('République centrafricaine', 'CF', (SELECT id FROM continents WHERE code = 'AF')),
('Tchad', 'TD', (SELECT id FROM continents WHERE code = 'AF')),
('Comores', 'KM', (SELECT id FROM continents WHERE code = 'AF')),
('Congo', 'CG', (SELECT id FROM continents WHERE code = 'AF')),
('République démocratique du Congo', 'CD', (SELECT id FROM continents WHERE code = 'AF')),
('Côte d''Ivoire', 'CI', (SELECT id FROM continents WHERE code = 'AF')),
('Djibouti', 'DJ', (SELECT id FROM continents WHERE code = 'AF')),
('Égypte', 'EG', (SELECT id FROM continents WHERE code = 'AF')),
('Érythrée', 'ER', (SELECT id FROM continents WHERE code = 'AF')),
('Eswatini', 'SZ', (SELECT id FROM continents WHERE code = 'AF')),
('Éthiopie', 'ET', (SELECT id FROM continents WHERE code = 'AF')),
('Gabon', 'GA', (SELECT id FROM continents WHERE code = 'AF')),
('Gambie', 'GM', (SELECT id FROM continents WHERE code = 'AF')),
('Ghana', 'GH', (SELECT id FROM continents WHERE code = 'AF')),
('Guinée', 'GN', (SELECT id FROM continents WHERE code = 'AF')),
('Guinée-Bissau', 'GW', (SELECT id FROM continents WHERE code = 'AF')),
('Guinée équatoriale', 'GQ', (SELECT id FROM continents WHERE code = 'AF')),
('Kenya', 'KE', (SELECT id FROM continents WHERE code = 'AF')),
('Lesotho', 'LS', (SELECT id FROM continents WHERE code = 'AF')),
('Liberia', 'LR', (SELECT id FROM continents WHERE code = 'AF')),
('Libye', 'LY', (SELECT id FROM continents WHERE code = 'AF')),
('Madagascar', 'MG', (SELECT id FROM continents WHERE code = 'AF')),
('Malawi', 'MW', (SELECT id FROM continents WHERE code = 'AF')),
('Mali', 'ML', (SELECT id FROM continents WHERE code = 'AF')),
('Maroc', 'MA', (SELECT id FROM continents WHERE code = 'AF')),
('Maurice', 'MU', (SELECT id FROM continents WHERE code = 'AF')),
('Mauritanie', 'MR', (SELECT id FROM continents WHERE code = 'AF')),
('Mayotte', 'YT', (SELECT id FROM continents WHERE code = 'AF')),
('Mozambique', 'MZ', (SELECT id FROM continents WHERE code = 'AF')),
('Namibie', 'NA', (SELECT id FROM continents WHERE code = 'AF')),
('Niger', 'NE', (SELECT id FROM continents WHERE code = 'AF')),
('Nigéria', 'NG', (SELECT id FROM continents WHERE code = 'AF')),
('Ouganda', 'UG', (SELECT id FROM continents WHERE code = 'AF')),
('Réunion', 'RE', (SELECT id FROM continents WHERE code = 'AF')),
('Rwanda', 'RW', (SELECT id FROM continents WHERE code = 'AF')),
('Sahara occidental', 'EH', (SELECT id FROM continents WHERE code = 'AF')),
('Sao Tomé-et-Principe', 'ST', (SELECT id FROM continents WHERE code = 'AF')),
('Sénégal', 'SN', (SELECT id FROM continents WHERE code = 'AF')),
('Seychelles', 'SC', (SELECT id FROM continents WHERE code = 'AF')),
('Sierra Leone', 'SL', (SELECT id FROM continents WHERE code = 'AF')),
('Somalie', 'SO', (SELECT id FROM continents WHERE code = 'AF')),
('Soudan', 'SD', (SELECT id FROM continents WHERE code = 'AF')),
('Soudan du Sud', 'SS', (SELECT id FROM continents WHERE code = 'AF')),
('Tanzanie', 'TZ', (SELECT id FROM continents WHERE code = 'AF')),
('Togo', 'TG', (SELECT id FROM continents WHERE code = 'AF')),
('Tunisie', 'TN', (SELECT id FROM continents WHERE code = 'AF')),
('Zambie', 'ZM', (SELECT id FROM continents WHERE code = 'AF')),
('Zimbabwe', 'ZW', (SELECT id FROM continents WHERE code = 'AF')),

-- Europe (EU)
('Albanie', 'AL', (SELECT id FROM continents WHERE code = 'EU')),
('Allemagne', 'DE', (SELECT id FROM continents WHERE code = 'EU')),
('Andorre', 'AD', (SELECT id FROM continents WHERE code = 'EU')),
('Arménie', 'AM', (SELECT id FROM continents WHERE code = 'EU')),
('Autriche', 'AT', (SELECT id FROM continents WHERE code = 'EU')),
('Belgique', 'BE', (SELECT id FROM continents WHERE code = 'EU')),
('Biélorussie', 'BY', (SELECT id FROM continents WHERE code = 'EU')),
('Bosnie-Herzégovine', 'BA', (SELECT id FROM continents WHERE code = 'EU')),
('Bulgarie', 'BG', (SELECT id FROM continents WHERE code = 'EU')),
('Chypre', 'CY', (SELECT id FROM continents WHERE code = 'EU')),
('Croatie', 'HR', (SELECT id FROM continents WHERE code = 'EU')),
('Danemark', 'DK', (SELECT id FROM continents WHERE code = 'EU')),
('Espagne', 'ES', (SELECT id FROM continents WHERE code = 'EU')),
('Estonie', 'EE', (SELECT id FROM continents WHERE code = 'EU')),
('Finlande', 'FI', (SELECT id FROM continents WHERE code = 'EU')),
('France', 'FR', (SELECT id FROM continents WHERE code = 'EU')),
('Géorgie', 'GE', (SELECT id FROM continents WHERE code = 'EU')),
('Grèce', 'GR', (SELECT id FROM continents WHERE code = 'EU')),
('Hongrie', 'HU', (SELECT id FROM continents WHERE code = 'EU')),
('Irlande', 'IE', (SELECT id FROM continents WHERE code = 'EU')),
('Islande', 'IS', (SELECT id FROM continents WHERE code = 'EU')),
('Italie', 'IT', (SELECT id FROM continents WHERE code = 'EU')),
('Kazakhstan', 'KZ', (SELECT id FROM continents WHERE code = 'EU')),
('Kosovo', 'XK', (SELECT id FROM continents WHERE code = 'EU')),
('Lettonie', 'LV', (SELECT id FROM continents WHERE code = 'EU')),
('Liechtenstein', 'LI', (SELECT id FROM continents WHERE code = 'EU')),
('Lituanie', 'LT', (SELECT id FROM continents WHERE code = 'EU')),
('Luxembourg', 'LU', (SELECT id FROM continents WHERE code = 'EU')),
('Macédoine du Nord', 'MK', (SELECT id FROM continents WHERE code = 'EU')),
('Malte', 'MT', (SELECT id FROM continents WHERE code = 'EU')),
('Moldavie', 'MD', (SELECT id FROM continents WHERE code = 'EU')),
('Monaco', 'MC', (SELECT id FROM continents WHERE code = 'EU')),
('Monténégro', 'ME', (SELECT id FROM continents WHERE code = 'EU')),
('Norvège', 'NO', (SELECT id FROM continents WHERE code = 'EU')),
('Pays-Bas', 'NL', (SELECT id FROM continents WHERE code = 'EU')),
('Pologne', 'PL', (SELECT id FROM continents WHERE code = 'EU')),
('Portugal', 'PT', (SELECT id FROM continents WHERE code = 'EU')),
('Roumanie', 'RO', (SELECT id FROM continents WHERE code = 'EU')),
('Royaume-Uni', 'GB', (SELECT id FROM continents WHERE code = 'EU')),
('Russie', 'RU', (SELECT id FROM continents WHERE code = 'EU')),
('Saint-Marin', 'SM', (SELECT id FROM continents WHERE code = 'EU')),
('Serbie', 'RS', (SELECT id FROM continents WHERE code = 'EU')),
('Slovaquie', 'SK', (SELECT id FROM continents WHERE code = 'EU')),
('Slovénie', 'SI', (SELECT id FROM continents WHERE code = 'EU')),
('Suède', 'SE', (SELECT id FROM continents WHERE code = 'EU')),
('Suisse', 'CH', (SELECT id FROM continents WHERE code = 'EU')),
('Tchéquie', 'CZ', (SELECT id FROM continents WHERE code = 'EU')),
('Ukraine', 'UA', (SELECT id FROM continents WHERE code = 'EU')),
('Vatican', 'VA', (SELECT id FROM continents WHERE code = 'EU')),

-- Amérique du Nord (NA)
('Antigua-et-Barbuda', 'AG', (SELECT id FROM continents WHERE code = 'NA')),
('Bahamas', 'BS', (SELECT id FROM continents WHERE code = 'NA')),
('Barbade', 'BB', (SELECT id FROM continents WHERE code = 'NA')),
('Belize', 'BZ', (SELECT id FROM continents WHERE code = 'NA')),
('Canada', 'CA', (SELECT id FROM continents WHERE code = 'NA')),
('Costa Rica', 'CR', (SELECT id FROM continents WHERE code = 'NA')),
('Cuba', 'CU', (SELECT id FROM continents WHERE code = 'NA')),
('Dominique', 'DM', (SELECT id FROM continents WHERE code = 'NA')),
('États-Unis', 'US', (SELECT id FROM continents WHERE code = 'NA')),
('Grenade', 'GD', (SELECT id FROM continents WHERE code = 'NA')),
('Guatemala', 'GT', (SELECT id FROM continents WHERE code = 'NA')),
('Haïti', 'HT', (SELECT id FROM continents WHERE code = 'NA')),
('Honduras', 'HN', (SELECT id FROM continents WHERE code = 'NA')),
('Jamaïque', 'JM', (SELECT id FROM continents WHERE code = 'NA')),
('Mexique', 'MX', (SELECT id FROM continents WHERE code = 'NA')),
('Nicaragua', 'NI', (SELECT id FROM continents WHERE code = 'NA')),
('Panama', 'PA', (SELECT id FROM continents WHERE code = 'NA')),
('République dominicaine', 'DO', (SELECT id FROM continents WHERE code = 'NA')),
('Saint-Christophe-et-Niévès', 'KN', (SELECT id FROM continents WHERE code = 'NA')),
('Sainte-Lucie', 'LC', (SELECT id FROM continents WHERE code = 'NA')),
('Saint-Vincent-et-les-Grenadines', 'VC', (SELECT id FROM continents WHERE code = 'NA')),
('Salvador', 'SV', (SELECT id FROM continents WHERE code = 'NA')),
('Trinité-et-Tobago', 'TT', (SELECT id FROM continents WHERE code = 'NA')),

-- Amérique du Sud (SA)
('Argentine', 'AR', (SELECT id FROM continents WHERE code = 'SA')),
('Bolivie', 'BO', (SELECT id FROM continents WHERE code = 'SA')),
('Brésil', 'BR', (SELECT id FROM continents WHERE code = 'SA')),
('Chili', 'CL', (SELECT id FROM continents WHERE code = 'SA')),
('Colombie', 'CO', (SELECT id FROM continents WHERE code = 'SA')),
('Équateur', 'EC', (SELECT id FROM continents WHERE code = 'SA')),
('Guyana', 'GY', (SELECT id FROM continents WHERE code = 'SA')),
('Paraguay', 'PY', (SELECT id FROM continents WHERE code = 'SA')),
('Pérou', 'PE', (SELECT id FROM continents WHERE code = 'SA')),
('Suriname', 'SR', (SELECT id FROM continents WHERE code = 'SA')),
('Uruguay', 'UY', (SELECT id FROM continents WHERE code = 'SA')),
('Venezuela', 'VE', (SELECT id FROM continents WHERE code = 'SA')),

-- Asie (AS)
('Afghanistan', 'AF', (SELECT id FROM continents WHERE code = 'AS')),
('Arabie saoudite', 'SA', (SELECT id FROM continents WHERE code = 'AS')),
('Arménie', 'AM', (SELECT id FROM continents WHERE code = 'AS')),
('Azerbaïdjan', 'AZ', (SELECT id FROM continents WHERE code = 'AS')),
('Bahreïn', 'BH', (SELECT id FROM continents WHERE code = 'AS')),
('Bangladesh', 'BD', (SELECT id FROM continents WHERE code = 'AS')),
('Bhoutan', 'BT', (SELECT id FROM continents WHERE code = 'AS')),
('Birmanie', 'MM', (SELECT id FROM continents WHERE code = 'AS')),
('Brunei', 'BN', (SELECT id FROM continents WHERE code = 'AS')),
('Cambodge', 'KH', (SELECT id FROM continents WHERE code = 'AS')),
('Chine', 'CN', (SELECT id FROM continents WHERE code = 'AS')),
('Corée du Nord', 'KP', (SELECT id FROM continents WHERE code = 'AS')),
('Corée du Sud', 'KR', (SELECT id FROM continents WHERE code = 'AS')),
('Émirats arabes unis', 'AE', (SELECT id FROM continents WHERE code = 'AS')),
('Géorgie', 'GE', (SELECT id FROM continents WHERE code = 'AS')),
('Inde', 'IN', (SELECT id FROM continents WHERE code = 'AS')),
('Indonésie', 'ID', (SELECT id FROM continents WHERE code = 'AS')),
('Irak', 'IQ', (SELECT id FROM continents WHERE code = 'AS')),
('Iran', 'IR', (SELECT id FROM continents WHERE code = 'AS')),
('Israël', 'IL', (SELECT id FROM continents WHERE code = 'AS')),
('Japon', 'JP', (SELECT id FROM continents WHERE code = 'AS')),
('Jordanie', 'JO', (SELECT id FROM continents WHERE code = 'AS')),
('Kazakhstan', 'KZ', (SELECT id FROM continents WHERE code = 'AS')),
('Kirghizistan', 'KG', (SELECT id FROM continents WHERE code = 'AS')),
('Koweït', 'KW', (SELECT id FROM continents WHERE code = 'AS')),
('Laos', 'LA', (SELECT id FROM continents WHERE code = 'AS')),
('Liban', 'LB', (SELECT id FROM continents WHERE code = 'AS')),
('Malaisie', 'MY', (SELECT id FROM continents WHERE code = 'AS')),
('Maldives', 'MV', (SELECT id FROM continents WHERE code = 'AS')),
('Mongolie', 'MN', (SELECT id FROM continents WHERE code = 'AS')),
('Népal', 'NP', (SELECT id FROM continents WHERE code = 'AS')),
('Oman', 'OM', (SELECT id FROM continents WHERE code = 'AS')),
('Ouzbékistan', 'UZ', (SELECT id FROM continents WHERE code = 'AS')),
('Pakistan', 'PK', (SELECT id FROM continents WHERE code = 'AS')),
('Palestine', 'PS', (SELECT id FROM continents WHERE code = 'AS')),
('Philippines', 'PH', (SELECT id FROM continents WHERE code = 'AS')),
('Qatar', 'QA', (SELECT id FROM continents WHERE code = 'AS')),
('Russie', 'RU', (SELECT id FROM continents WHERE code = 'AS')),
('Singapour', 'SG', (SELECT id FROM continents WHERE code = 'AS')),
('Sri Lanka', 'LK', (SELECT id FROM continents WHERE code = 'AS')),
('Syrie', 'SY', (SELECT id FROM continents WHERE code = 'AS')),
('Tadjikistan', 'TJ', (SELECT id FROM continents WHERE code = 'AS')),
('Taïwan', 'TW', (SELECT id FROM continents WHERE code = 'AS')),
('Thaïlande', 'TH', (SELECT id FROM continents WHERE code = 'AS')),
('Timor oriental', 'TL', (SELECT id FROM continents WHERE code = 'AS')),
('Turkménistan', 'TM', (SELECT id FROM continents WHERE code = 'AS')),
('Turquie', 'TR', (SELECT id FROM continents WHERE code = 'AS')),
('Viêt Nam', 'VN', (SELECT id FROM continents WHERE code = 'AS')),
('Yémen', 'YE', (SELECT id FROM continents WHERE code = 'AS')),

-- Océanie (OC)
('Australie', 'AU', (SELECT id FROM continents WHERE code = 'OC')),
('Fidji', 'FJ', (SELECT id FROM continents WHERE code = 'OC')),
('Îles Marshall', 'MH', (SELECT id FROM continents WHERE code = 'OC')),
('Îles Salomon', 'SB', (SELECT id FROM continents WHERE code = 'OC')),
('Kiribati', 'KI', (SELECT id FROM continents WHERE code = 'OC')),
('Micronésie', 'FM', (SELECT id FROM continents WHERE code = 'OC')),
('Nauru', 'NR', (SELECT id FROM continents WHERE code = 'OC')),
('Nouvelle-Zélande', 'NZ', (SELECT id FROM continents WHERE code = 'OC')),
('Palaos', 'PW', (SELECT id FROM continents WHERE code = 'OC')),
('Papouasie-Nouvelle-Guinée', 'PG', (SELECT id FROM continents WHERE code = 'OC')),
('Samoa', 'WS', (SELECT id FROM continents WHERE code = 'OC')),
('Tonga', 'TO', (SELECT id FROM continents WHERE code = 'OC')),
('Tuvalu', 'TV', (SELECT id FROM continents WHERE code = 'OC')),
('Vanuatu', 'VU', (SELECT id FROM continents WHERE code = 'OC'))
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, continent_id = EXCLUDED.continent_id;

-- 4. Index pour performances
CREATE INDEX IF NOT EXISTS idx_countries_continent_id ON public.countries(continent_id);
CREATE INDEX IF NOT EXISTS idx_countries_name ON public.countries(name);
CREATE INDEX IF NOT EXISTS idx_countries_code ON public.countries(code);
CREATE INDEX IF NOT EXISTS idx_cities_country_id ON public.cities(country_id);
CREATE INDEX IF NOT EXISTS idx_cities_name ON public.cities(name);

-- =====================================================
-- FIN DE LA MIGRATION
-- =====================================================